// Display text only. English card names remain the identifiers used by game rules and artwork.
export const arabicCardText: Record<string, string> = {
  "Airknight Parshath": "فارس السماء بارشاث",
  "Baby Dragon": "التنين الصغير",
  "Battle Warrior": "محارب المعركة",
  "Block Attack": "إيقاف الهجوم",
  "Flame Manipulator": "متحكم اللهب",
  "Flame Swordsman": "سياف اللهب",
  "Goblin Attack Force": "قوة هجوم الغوبلن",
  "Graceful Dice": "النرد الرشيق",
  "Jinzo": "جينزو",
  "Kunai with Chain": "كوناي مع سلسلة",
  "Legendary Sword": "السيف الأسطوري",
  "Monster Reborn": "إحياء الوحوش",
  "Polymerization": "الدمج",
  "Red-Eyes Black Dragon": "التنين الأسود أحمر العينين",
  "Blue-Eyes White Dragon": "التنين الأبيض أزرق العينين",
  "Salamandra": "سالاماندرا",
  "Scapegoat": "كبش الفداء",
  "Skull Dice": "نرد الجمجمة",
  "Swordsman of Landstar": "سياف لاندستار",
  "Thousand Dragon": "تنين الألف عام",
  "Time Wizard": "ساحر الزمن",
  "Trap Hole": "حفرة الفخ",
  "Time Wizard of Tomorrow": "ساحر زمن الغد",
  "The Claw of Hermos": "مخلب هيرموس",
  "Mirror Force": "قوة المرآة",
  "Copycat": "المقلد",
  "Fiber Jar": "جرة الألياف",
  "Red-Eyes Black Metal Dragon": "التنين المعدني الأسود أحمر العينين",
  "Alligator's Sword": "سيف التمساح",
  "Alligator's Sword Dragon": "تنين سيف التمساح",
  "Axe Raider": "مغير الفأس",
  "Change of Heart": "تغيير القلب",
  "Trap Hole of Spikes": "حفرة الأشواك",
  "Foolish Burial": "الدفن الأحمق",
  "Gamble": "المقامرة",
  "Black Skull Dragon": "تنين الجمجمة السوداء",
  "Gearfried the Iron Knight": "جيرفريد الفارس الحديدي",
  "Gearfried the Swordmaster": "جيرفريد سيد السيوف",
  "Fairy Box": "صندوق الجنيات",
  "Dark Hole": "الثقب الأسود",
  "Drop Off": "إسقاط",
  "Giant Trunade": "الإعصار العملاق",
  "Gilti-Gearfried the Magical Steel Knight": "جيلتي جيرفريد فارس الفولاذ السحري",
  "Blue Flame Swordsman": "سياف اللهب الأزرق",
  "Card of Sanctity": "بطاقة القداسة",
  "Gilford the Lightning": "جيلفورد الصاعقة",
  "Giltia the D. Knight - Soul Spear": "جيلتيا الفارس - رمح الروح",
  "Pot of Greed": "جرة الطمع",
  "Marauding Captain": "القائد المغير",
  "Magical Arm Shield": "درع الذراع السحرية",
  "Panther Warrior": "محارب النمر",
  "Stray Lambs": "الحملان الضالة",
  "Little-Winguard": "حارس الجناح الصغير",
  "Metalmorph": "التحول المعدني",
  "Question": "سؤال",
  "Sakuretsu Armor": "درع ساكوريتسو",
  "Roulette Spider": "عنكبوت الروليت",
  "Rocket Warrior": "المحارب الصاروخي",
  "Nutrient Z": "المغذي زد",
  "Release Restraint": "فك القيود",
  "Rocket Hermos Cannon": "مدفع هيرموس الصاروخي",
  "Red-Eyes Black Dragon Sword": "سيف التنين الأسود أحمر العينين",
  "Shield & Sword": "الدرع والسيف",
  "Lightning Blade": "نصل البرق",
  "Sword Hunter": "صياد السيوف",
  "Graverobber": "سارق القبور",
  "Hayabusa Knight": "فارس هايابوسا",
  "The Fiend Megacyber": "الشيطان ميغاسايبر",
  "Time Magic Hammer": "مطرقة سحر الزمن",
  "The Warrior Returning Alive": "عودة المحارب حيًا",
  "Dark Magician": "ساحر الظلام",
  "Dark Magician Girl": "فتاة ساحر الظلام",
  "Magician of Black Chaos": "ساحر الفوضى السوداء",
  "Buster Blader": "باستر بليدر",
  "Summoned Skull": "الجمجمة المستدعاة",
  "Gaia The Fierce Knight": "غايا الفارس الشرس",
  "Curse of Dragon": "لعنة التنين",
  "Gaia The Dragon Champion": "غايا بطل التنانين",
  "Black Luster Soldier": "جندي البريق الأسود",
  "Black Luster Ritual": "طقوس البريق الأسود",
  "Celtic Guardian": "الحارس السلتي",
  "Mystical Elf": "الجنية الغامضة",
  "Giant Soldier of Stone": "الجندي الحجري العملاق",
  "Beaver Warrior": "محارب القندس",
  "Feral Imp": "العفريت المتوحش",
  "Silver Fang": "الناب الفضي",
  "Gazelle the King of Mythical Beasts": "غزال ملك الوحوش الأسطورية",
  "Berfomet": "برفوميت",
  "Chimera the Flying Mythical Beast": "كيميرا الوحش الأسطوري الطائر",
  "King's Knight": "فارس الملك",
  "Queen's Knight": "فارسة الملكة",
  "Jack's Knight": "فارس جاك",
  "Exodia the Forbidden One": "إكسوديا المحظور",
  "Right Arm of the Forbidden One": "الذراع اليمنى للمحظور",
  "Left Arm of the Forbidden One": "الذراع اليسرى للمحظور",
  "Right Leg of the Forbidden One": "الساق اليمنى للمحظور",
  "Left Leg of the Forbidden One": "الساق اليسرى للمحظور",
  "Swords of Revealing Light": "سيوف الضوء الكاشف",
  "Brain Control": "السيطرة على العقل",
  "Mystical Space Typhoon": "إعصار الفضاء الغامض",
  "Card Destruction": "تدمير البطاقات",
  "Magical Hats": "القبعات السحرية",
  "Magic Cylinder": "الأسطوانة السحرية",
  "Spellbinding Circle": "دائرة الأسر السحرية",
  "De-Spell": "إبطال السحر",
  "Beta The Magnet Warrior": "بيتا المحارب المغناطيسي",
  "The Eye of Timaeus": "عين تيمايوس",
  "Slifer the Sky Dragon": "سلايفر تنين السماء",
  "Obelisk the Tormentor": "أوبيليسك المعذب",
  "The Winged Dragon of Ra": "تنين رع المجنح",
  "The Fang of Critias": "ناب كريتياس",
  "Dark Magician Girl the Dragon Knight": "فتاة ساحر الظلام فارسة التنين",
  "Dark Magician the Dragon Knight": "ساحر الظلام فارس التنين",
  "Dark Paladin": "فارس الظلام",
  "Raigeki": "رايغيكي",
  "De-Fusion": "فك الدمج",
  "Catapult Turtle": "سلحفاة المنجنيق",
  "Amulet Dragon": "تنين التميمة",
  "Arcana Knight Joker": "جوكر فارس أركانا",
  "Kuriboh": "كوريبو",
  "Magician of Faith": "ساحرة الإيمان",
  "Ancient Rules": "القواعد القديمة",
  "Black Luster Soldier - Envoy of the Beginning": "جندي البريق الأسود - مبعوث البداية",
  "Celtic Guard of Noble Arms": "الحارس السلتي ذو الأسلحة النبيلة",
  "Dark Magician of Chaos": "ساحر الفوضى المظلم",
  "Magician's Valkyria": "فالكيريا الساحر",
  "Graceful Charity": "الصدقة الكريمة",
  "Witch of the Black Forest": "ساحرة الغابة السوداء",
  "Alpha The Magnet Warrior": "ألفا المحارب المغناطيسي",
  "Big Shield Gardna": "غاردنا ذو الدرع الكبير",
  "Black Illusion": "الوهم الأسود",
  "Torrential Tribute": "تضحية السيل الجارف",
  "Tribute": "تضحية",
  "Tribute Summon": "استدعاء بالتضحية",
  "You can Tribute 3 monsters to Tribute Summon (but not Set) this card. If Summoned this way: Destroy all monsters your opponent controls.": "يمكنك التضحية بـ3 وحوش لاستدعاء هذه البطاقة بالتضحية (ولكن ليس وضعها مقلوبة). إذا استُدعيت بهذه الطريقة: دمر جميع الوحوش التي يتحكم بها خصمك.",
  "Requires 3 Tributes to Normal Summon (cannot be Normal Set). This card's Normal Summon cannot be negated. When Normal Summoned, cards and effects cannot be activated. Neither player can target this card with card effects. Once per turn, during the End Phase, if this card was Special Summoned: Send it to the GY. You can Tribute 2 monsters; destroy all monsters your opponent controls. This card cannot declare an attack the turn this effect is activated.": "يتطلب الاستدعاء العادي لهذه البطاقة التضحية بـ3 وحوش (ولا يمكن وضعها مقلوبة بشكل عادي). لا يمكن إبطال استدعائها العادي. عند استدعائها بشكل عادي، لا يمكن تفعيل البطاقات أو التأثيرات. لا يمكن لأي لاعب استهداف هذه البطاقة بتأثيرات البطاقات. مرة واحدة في كل دور، خلال مرحلة النهاية، إذا استُدعيت هذه البطاقة استدعاءً خاصًا: أرسلها إلى المقبرة. يمكنك التضحية بوحشين؛ دمر جميع الوحوش التي يتحكم بها خصمك. لا يمكن لهذه البطاقة إعلان هجوم خلال الدور الذي يُفعَّل فيه هذا التأثير.",
  "Valkyrion the Magna Warrior": "فالكيريون المحارب المغناطيسي",
  "Winged Dragon, Guardian of the Fortress #1": "التنين المجنح حارس القلعة رقم 1",
  "Dark Renewal": "التجديد المظلم",
  "Black Magic Ritual": "طقوس السحر الأسود",
  "Bond Between Teacher and Student": "رابطة المعلم والتلميذ",
  "Dark Magic Attack": "هجوم السحر الأسود",
  "Dark Magic Curtain": "ستار السحر الأسود",
  "Dark Magic Veil": "حجاب السحر الأسود",
  "Double Spell": "السحر المزدوج",
  "Exchange": "التبادل",
  "Gamma the Magnet Warrior": "غاما المحارب المغناطيسي",
  "Griffore": "غريفور",
  "Heavy Storm": "العاصفة العاتية",
  "Horn Imp": "العفريت ذو القرون",
  "Horn of the Unicorn": "قرن وحيد القرن",
  "Knight's Title": "لقب الفارس",
  "Koumori Dragon": "تنين كوموري",
  "Legendary Knight Critias": "الفارس الأسطوري كريتياس",
  "Legendary Knight Hermos": "الفارس الأسطوري هيرموس",
  "Legendary Knight Timaeus": "الفارس الأسطوري تيمايوس",
  "Magical Contract Door": "باب العقد السحري",
  "Spell Shattering Arrow": "سهم تحطيم السحر",
  "Sorcerer of Dark Magic": "مشعوذ السحر الأسود",
  "The Eye of Truth": "عين الحقيقة",
  "Sangan": "سانغان",
  "Shift": "تحويل",
  "Thousand Knives": "ألف سكين",
  "Snatch Steal": "الاستيلاء",
  "Timaeus the United Dragon": "تيمايوس التنين المتحد",
  "Aqua Chorus": "جوقة الماء",
  "Normal Monster": "وحش عادي",
  "Effect Monster": "وحش ذو تأثير",
  "Flip Effect Monster": "وحش ذو تأثير عند القلب",
  "Fusion Monster": "وحش دمج",
  "Ritual Monster": "وحش طقوس",
  "Ritual Effect Monster": "وحش طقوس ذو تأثير",
  "Spell Card": "بطاقة سحر",
  "Trap Card": "بطاقة فخ",
  "Draw 2 cards.": "اسحب بطاقتين.",
  "Destroy all monsters on the field.": "دمر جميع الوحوش الموجودة في الملعب.",
  "Destroy all monsters your opponent controls.": "دمر جميع الوحوش التي يتحكم بها خصمك.",
  "Send 1 monster from your Deck to the GY.": "أرسل وحشًا واحدًا من مجموعتك إلى المقبرة.",
  "FLIP: Each player shuffles all cards from their hand, field, and Graveyard into the Deck, then draws 5 cards.": "عند القلب: يعيد كل لاعب جميع البطاقات من يده وملعبه ومقبرته إلى مجموعته ويخلطها، ثم يسحب 5 بطاقات.",
  "This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.": "هذا التنين الأسطوري قوة هائلة للتدمير. يكاد يكون لا يُقهر، وقليلون جدًا واجهوا هذا المخلوق المهيب ونجوا ليرووا قصتهم."
};

export function normalizeArabicCardTerms(source: string, translation: string) {
  if (!/\btributes?\b/i.test(source)) return translation;
  return translation
    .replace(/التكريم/g, "التضحية")
    .replace(/تكريم/g, "التضحية بـ")
    .replace(/تحيات|تحية/g, "تضحيات");
}
