export type SavedCardSet = {
  id: string;
  name: string;
  description: string;
  cards: Array<{
    name: string;
    quantity?: number;
  }>;
};

export const defaultSavedCardSets: SavedCardSet[] = [
  {
    id: "joy-card-set",
    name: "Joy Card Set",
    description: "A starter import based on the supplied classic card-set image. Imports into Extra Cards for manual sorting.",
    cards: [
      { name: "Arcana Knight Joker" },
      { name: "Airknight Parshath" },
      { name: "Baby Dragon" },
      { name: "Battle Warrior" },
      { name: "Black Pendant" },
      { name: "Block Attack" },
      { name: "Blue-Eyes Toon Dragon", quantity: 2 },
      { name: "Brain Control" },
      { name: "Clown Zombie" },
      { name: "De-Spell" },
      { name: "Dragon Capture Jar" },
      { name: "Elegant Egotist" },
      { name: "Flame Manipulator" },
      { name: "Flame Swordsman" },
      { name: "Fusion Gate" },
      { name: "Gaia The Dragon Champion" },
      { name: "Giltia the D. Knight" },
      { name: "Goblin Attack Force", quantity: 2 },
      { name: "Graceful Charity" },
      { name: "Graceful Dice" },
      { name: "Harpie Lady Sisters" },
      { name: "Jinzo" },
      { name: "Karbonala Warrior" },
      { name: "Kunai with Chain" },
      { name: "Legendary Sword" },
      { name: "Magic Jammer" },
      { name: "Monster Reborn" },
      { name: "Mystical Space Typhoon" },
      { name: "Polymerization", quantity: 2 },
      { name: "Raigeki" },
      { name: "Raigeki Break" },
      { name: "Red-Eyes Black Dragon" },
      { name: "Remove Trap" },
      { name: "Salamandra" },
      { name: "Scapegoat" },
      { name: "Seven Tools of the Bandit" },
      { name: "Skull Dice" },
      { name: "Soul Exchange" },
      { name: "Swordsman of Landstar" },
      { name: "The Flute of Summoning Dragon" },
      { name: "Thousand Dragon" },
      { name: "Time Wizard", quantity: 2 },
      { name: "Toon Mermaid" },
      { name: "Toon Summoned Skull" },
      { name: "Trap Hole" }
    ]
  },
  {
    id: "exodia-card-set",
    name: "Exodia",
    description: "2025 Millennium Exodia deck from the supplied profile: 40-card Main Deck and 15-card Extra Deck. Imports into Extra Cards for manual sorting.",
    cards: [
      { name: "Right Leg of the Forbidden One" },
      { name: "Left Leg of the Forbidden One" },
      { name: "Right Arm of the Forbidden One" },
      { name: "Left Arm of the Forbidden One" },
      { name: "Exodia the Forbidden One" },
      { name: "Maxx \"C\"", quantity: 2 },
      { name: "Ash Blossom & Joyous Spring", quantity: 3 },
      { name: "Shield of the Millennium Dynasty", quantity: 3 },
      { name: "Dimension Shifter" },
      { name: "Golem that Guards the Millennium", quantity: 2 },
      { name: "Sengenjin Wakes from a Millennium", quantity: 3 },
      { name: "Heart of the Blue-Eyes", quantity: 3 },
      { name: "Triple Tactics Talent", quantity: 3 },
      { name: "Millennium Ankh", quantity: 3 },
      { name: "Wedju Temple", quantity: 2 },
      { name: "Super Polymerization", quantity: 3 },
      { name: "Obliterate!!! Blaze" },
      { name: "Infinite Impermanence", quantity: 3 },
      { name: "Exxod Fires of Rage", quantity: 2 },
      { name: "Angel Statue - Azurune" },
      { name: "Mudragon of the Swamp" },
      { name: "Garura, Wings of Resonant Life" },
      { name: "Predaplant Dragostapelia" },
      { name: "The Unstoppable Exodia Incarnate", quantity: 3 },
      { name: "Yubel - The Loving Defender Forever" },
      { name: "Knightmare Gryphon" },
      { name: "Knightmare Cerberus" },
      { name: "Knightmare Phoenix" },
      { name: "Aussa the Earth Charmer, Immovable" },
      { name: "S:P Little Knight" },
      { name: "Moon of the Closed Heaven" },
      { name: "Silhouhatte Rabbit" },
      { name: "Underworld Goddess of the Closed World" }
    ]
  },
  {
    id: "bakura-card-set",
    name: "Bakura",
    description: "Bakura card list from the supplied transcription and reference image. Imports into Extra Cards for manual sorting.",
    cards: [
      { name: "Axe of Despair" },
      { name: "Brain Control" },
      { name: "Call of the Earthbound" },
      { name: "Change of Heart" },
      { name: "Contract with the Dark Master", quantity: 2 },
      { name: "Cursed Twin Dolls" },
      { name: "Dark Elf" },
      { name: "Dark Hole" },
      { name: "Dark Master - Zorc" },
      { name: "Dark Necrofear" },
      { name: "Dark Spirit of the Silent", quantity: 3 },
      { name: "Destiny Board" },
      { name: "Doomcalibur Knight" },
      { name: "Ectoplasmer" },
      { name: "Exchange" },
      { name: "Fiend's Sanctuary" },
      { name: "Flame Manipulator" },
      { name: "Giant Trunade" },
      { name: "Grave Tablet" },
      { name: "Headless Knight" },
      { name: "Life Absorbing Machine" },
      { name: "Man-Eater Bug" },
      { name: "Mask of Darkness" },
      { name: "Melchid the Four-Face Beast" },
      { name: "Mirror Force" },
      { name: "Monster Reborn" },
      { name: "Morphing Jar" },
      { name: "Pot of Greed" },
      { name: "Premature Burial" },
      { name: "Sangan" },
      { name: "Spirit Elimination" },
      { name: "Spirit Message \"A\"" },
      { name: "Spirit Message \"I\"" },
      { name: "Spirit Message \"L\"" },
      { name: "Spirit Message \"N\"" },
      { name: "The Dark Door" },
      { name: "The Shallow Grave" },
      { name: "Torrential Tribute" },
      { name: "Tribute to the Doomed" },
      { name: "Wall of Revealing Light" },
      { name: "White Magical Hat" },
      { name: "Widespread Ruin" },
      { name: "Zoma the Spirit" }
    ]
  },
  {
    id: "kaiba-card-set",
    name: "Kaiba",
    description: "Kaiba card list from the supplied card positions. Imports into Extra Cards for manual sorting.",
    cards: [
      { name: "Obelisk the Tormentor" },
      { name: "XYZ-Dragon Cannon", quantity: 2 },
      { name: "Tribute to the Doomed" },
      { name: "Blade Knight" },
      { name: "Mystical Space Typhoon" },
      { name: "Cyber Jar" },
      { name: "Nobleman of Crossout" },
      { name: "Luster Dragon" },
      { name: "Dragon Dweller" },
      { name: "Interdimensional Matter Transporter" },
      { name: "Vorse Raider" },
      { name: "Double Coston", quantity: 2 },
      { name: "Kaiser Glider" },
      { name: "Lord of D." },
      { name: "Goblin Attack Force" },
      { name: "The Flute of Summoning Dragon" },
      { name: "Polymerization" },
      { name: "X-Head Cannon" },
      { name: "XY-Dragon Cannon" },
      { name: "XZ-Tank Cannon" },
      { name: "Enraged Battle Ox" },
      { name: "Kaiser Sea Horse", quantity: 2 },
      { name: "Paladin of White Dragon" },
      { name: "Blue-Eyes Toon Dragon" },
      { name: "Ryu-Kishin Powered" },
      { name: "Y-Dragon Head" },
      { name: "YZ-Dragon Tank" },
      { name: "Hyozanryu" },
      { name: "Peten the Dark Clown", quantity: 3 },
      { name: "White Dragon Ritual" },
      { name: "Saggi the Dark Clown" },
      { name: "Crush Card Virus" },
      { name: "Blue-Eyes Ultimate Dragon" },
      { name: "Dragon's Rage" },
      { name: "Different Dimension Dragon" },
      { name: "Z-Metal Tank" },
      { name: "Monster Reborn" },
      { name: "Five-Headed Dragon" },
      { name: "Blue-Eyes White Dragon", quantity: 3 },
      { name: "Dragon Master Knight" },
      { name: "Cave Dragon" },
      { name: "Giant Germ", quantity: 3 },
      { name: "La Jinn the Mystical Genie of the Lamp" },
      { name: "Enemy Controller" }
    ]
  }
];
